### ISSUE TITLE
N-grams lengths

### ISSUE THREAD

**Issue by rafaelanchieta** [freesunshine0316/sembleu#1]
My AMR inputs:

Reference
`(w / want-01 :ARG0 (b / boy) :ARG1 (g / go-01 :ARG0 b))`

Hypothesis
`(w / want-01 :ARG0 (b / boy) :ARG1 (g / go-01))`

N-grams lengths: 
Reference:

> [[NgramInst(ngram={1: [('want-01',), ('boy',), ('go-01',)], 2: [('want-01', ':ARG0', 'boy'), ('want-01', ':ARG1', 'go-01'), ('go-01', ':ARG0', 'boy')], 3: [('want-01', ':ARG1', 'go-01', ':ARG0', 'boy')]}, length=6)]]

Should not the length be equal to seven?

**Comment by freesunshine0316** [comment]
Hi 
"length" corresponds to the length of the structure, which is similar to the sentence length for regular BLEU. We use the number of nodes plus the number of edges as the "length" for an AMR.

**Comment by rafaelanchieta** [comment]
Hi.
Thank you!
